export const formSelect = {
  labelPositionSelect: [
    { label: "左对齐", value: "left" },
    { label: "右对齐", value: "right" },
    { label: "居上", value: "top" },
  ],
  formSize: [
    { label: "mini", value: "mini" },
    { label: "小", value: "small " },
    { label: "正常", value: "medium " },
  ],
};

export const form_item_default = {
  textInput: {
    type: "text",
    label: "标签名",
    disabled: false,
    readonly: false,
    value: "单行文本",
    fieldName: "字段名",
    placeholder: "请输入提示文字",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    clearable: true,
    icon: "",
    prepend: "",
    append: "",
    btnConfig: {
      name: "单行文本",
    },
  },
  textarea: {
    type: "textarea",
    rows: 3,
    label: "标签名",
    disabled: false,
    readonly: false,
    value: "多行文本",
    fieldName: "字段名",
    placeholder: "请输入提示文字",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    btnConfig: {
      name: "多行文本",
    },
  },
  number: {
    type: "number",
    label: "标签名",
    disabled: false,
    value: 1,
    fieldName: "字段名",
    step: 0,
    min: 0,
    max: 100,
    precision: 0,
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    btnConfig: {
      name: "计数器",
    },
  },
  password: {
    type: "password",
    label: "标签名",
    disabled: false,
    readonly: false,
    value: "",
    fieldName: "字段名",
    placeholder: "请输入密码",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    clearable: true,
    icon: "",
    prepend: "",
    append: "",
    btnConfig: {
      name: "密码输入框",
    },
  },
  select: {
    type: "select",
    label: "标签名",
    disabled: false,
    multiple: false,
    value: "",
    fieldName: "字段名",
    placeholder: "请输入提示文字",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    clearable: true,
    options: [
      { label: "选项1", value: "1" },
      { label: "选项2", value: "2" },
    ],
    btnConfig: {
      name: "下拉选择器",
    },
  },
  radio: {
    type: "radio",
    label: "标签名",
    disabled: false,
    value: "",
    fieldName: "字段名",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    border: false,
    button: false,
    options: [
      { label: "选项1", value: "1" },
      { label: "选项2", value: "2" },
    ],
    btnConfig: {
      name: "单选按钮组",
    },
  },
  checkbox: {
    type: "checkbox",
    label: "标签名",
    disabled: false,
    value: [],
    fieldName: "字段名",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    border: false,
    button: false,
    min: 0,
    max: 2,
    options: [
      { label: "选项1", value: "1" },
      { label: "选项2", value: "2" },
    ],
    btnConfig: {
      name: "多选按钮组",
    },
  },
  switch: {
    type: "switch",
    label: "标签名",
    disabled: false,
    value: true,
    fieldName: "字段名",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    btnConfig: {
      name: "开关",
    },
  },
  slider: {
    type: "slider",
    label: "标签名",
    disabled: false,
    value: 0,
    fieldName: "字段名",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    min: 0,
    max: 100,
    step: 5,
    showStops: false,
    btnConfig: {
      name: "滑块",
    },
  },
  time: {
    type: "time",
    label: "标签名",
    disabled: false,
    value: new Date(),
    fieldName: "字段名",
    placeholder: "请输入提示文字",
    rules: [],
    readonly: false,
    span: 24,
    labelWidth: 100,
    require: true,
    btnConfig: {
      name: "时间选择",
    },
  },
  timepicker: {
    type: "timepicker",
    label: "标签名",
    disabled: false,
    value: [new Date(), new Date()],
    startPlaceholder: "开始提示文字",
    endPlaceholder: "结束提示文字",
    rangeSeparator: "至",
    fieldName: "字段名",
    rules: [],
    readonly: false,
    span: 24,
    labelWidth: 100,
    require: true,
    btnConfig: {
      name: "时间范围选择",
    },
  },
  datetimepicker: {
    type: "datetimepicker",
    label: "标签名",
    disabled: false,
    value: [new Date(), new Date()],
    startPlaceholder: "开始提示文字",
    endPlaceholder: "结束提示文字",
    rangeSeparator: "至",
    fieldName: "字段名",
    rules: [],
    readonly: false,
    span: 24,
    labelWidth: 100,
    require: true,
    btnConfig: {
      name: "日期范围选择",
    },
  },
  datetime: {
    type: "datetime",
    label: "标签名",
    disabled: false,
    value: new Date(),
    fieldName: "字段名",
    placeholder: "请输入提示文字",
    rules: [],
    readonly: false,
    span: 24,
    labelWidth: 100,
    require: true,
    btnConfig: {
      name: "日期选择",
    },
  },
  rate: {
    type: "rate",
    label: "标签名",
    disabled: false,
    value: 5,
    allowHalf: false,
    fieldName: "字段名",
    rules: [],
    span: 24,
    labelWidth: 100,
    require: true,
    texts: ["极差", "失望", "一般", "满意", "惊喜"],
    btnConfig: {
      name: "评分",
    },
  },
};
